### ISSUE TITLE
IndexError when saving a session

### ISSUE THREAD

**Issue by paulmueller** [FCS-analysis/PyCorrFit#154]
![save-session-bug](https://cloud.githubusercontent.com/assets/2853022/12426429/ec50b1e6-bed9-11e5-9139-f68dc9b4d519.png)

Opening that session (reference 2016-01-19) and saving it results in the error:

```python
Traceback (most recent call last):
  File "pycorrfit/gui/frontend.py", line 1583, in OnSaveSession
    float(corr.fit_results["fit error estimation"][ii]) ])
IndexError: list index out of range
```

**Comment by paulmueller** [comment]
@weidemann This should be fixed in the developmental release: 


@paulmueller This is related to #122 and #124. It is unclear why the number of fitting parameters should not match up with the number of errors for the fitting parameters.

**Comment by weidemann** [comment]
Happened again after "save as" with a different name that the parent session could not be saved anymore. Maybe coincidence maybe related.

**Comment by paulmueller** [comment]
I don't understand. Did you use the new build that I linked above?

**Comment by weidemann** [comment]
probably not. I am using the last official release 0.9.7 for Windows 64 bit

**Comment by weidemann** [comment]
ok, got it. 0.9.7.dev1 works
