### ISSUE TITLE
Allow to abort batch fitting procedure

### ISSUE THREAD

**Issue by paulmueller** [FCS-analysis/PyCorrFit#155]
Large data sets take an unknown amount of time to fit. Add a progressbar.

**Comment by weidemann** [comment]
not only batch fitting, fitting in general.

**Comment by weidemann** [comment]
Abort function would especially enhance the performance if the current pages during batch fitting would be displayed in some "progress monitor box". This allows not only to estimate the remaining number of non-fitted pages, it can be also used to identify obstructive pages and thus bad data within the batch.
