### ISSUE TITLE
Installation failures on Windows 8/10

### ISSUE THREAD

**Issue by pdebeule** [FCS-analysis/PyCorrFit#160]
First, thanks for sharing this useful code.
Yesterday, I spent time some with a Python expert to get your code running on a Win 8/10 64-bit machine, using Anaconda2 2.5.0 with subsequent installation of wxpython through "conda install wxpython" and pycorrfit through "pip install pycorrfit[GUI]".
We stumbled on a variety of issues: numpy could not be found by the wxpython. After solving that by adjusting the wxpython code, pycorrfit launched, but loading a Zeiss .fcs data file gave up more wxpython errors.
Is there an easy fix to this, or is it best to install the exact package list as detailed in the Wiki?
Thanks, Pieter

**Comment by paulmueller** [comment]
Hi, are you aware of the binary installers?

https://github.com/FCS-analysis/PyCorrFit/releases

If, for some reason, you **need** to run PyCorrFit from source, I recommend installing the exact packages as described in the Wiki. Try Numpy 1.8 for a start.

**Comment by pdebeule** [comment]
No. This works great. Thanks.
Don't know why I did not find this link. I am pretty new to GitHub....
