### ISSUE TITLE
mathematical expression of models

### ISSUE THREAD

**Issue by polilinkerr** [FCS-analysis/PyCorrFit#162]
First of all, thanks for your software. It is great tool to analyse my data :)
In PyCorrFit we have possibility using many models.
I am curious how mathematical expressions of these models look like ( e.g. Gaussian with double triplet T+T+3D+2D)
I would appreciate your quick response :)
Regards,

**Comment by paulmueller** [comment]
You can find most of the model functions in the documentation of PyCorrFit.
https://github.com/FCS-analysis/PyCorrFit/wiki/PyCorrFit_doc.pdf

The second triplet component is simply multiplied to the expression, for instance:

https://github.com/FCS-analysis/PyCorrFit/blob/master/pycorrfit/models/model_confocal_tt_3d_2d.py#L75
