### ISSUE TITLE
pdf fails to build with new latex 

### ISSUE THREAD

**Issue by mestia** [FCS-analysis/PyCorrFit#163]
pdflatex fails due  to deprecated commands on Debian unstable.

pdfTeX 3.14159265-2.6-1.40.17 (TeX Live 2016/Debian)

The full PyCorrFit_doc.log log: http://pastebin.ubuntu.com/16548360/

Thanks, 
Alex

**Comment by paulmueller** [comment]
I replaced the "\rm" commands. Could you try again with the develop branch?

**Comment by mestia** [comment]
Thanks, now it is working.
