### ISSUE TITLE
Not able to load ASC file 

### ISSUE THREAD

**Issue by MithraNIT** [FCS-analysis/PyCorrFit#169]
When I try to load the .ASC extension file, I am getting the following error. I am using windows 34 bit OS. 
![capture](https://user-images.githubusercontent.com/30114065/28114053-c1e17552-671c-11e7-9799-0504a68a345d.JPG)

**Comment by paulmueller** [comment]
The format of this .asc file is not supported by PyCorrFit. Please attach the file (GitHub supports .zip file attachments) to this issue. I cannot promise you to implement support for this file format any time soon. I am working on other projects and will have to do it in my free time.

**Comment by MithraNIT** [comment]
Dear Sir,
This is the file from the ALV correlator (ALV, GmBH Germany). I just wanted to know if I am missing any steps. Should I attach a single file in the attachment? I understand you have a very busy schedule and I appreciate the reply.
Thanks

**Comment by paulmueller** [comment]
Yes, please attach a file. You will probably have to put it in a zip archive to be able to attach it (see https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/).

**Comment by MithraNIT** [comment]
I have attached the file.
Thanks
[1.zip](https://github.com/FCS-analysis/PyCorrFit/files/1142390/1.zip)

**Comment by paulmueller** [comment]
The file now loads with the latest development version. You can download it here:
https://ci.appveyor.com/project/paulmueller/pycorrfit/build/job/lauuooh523nmtq0q/artifacts

If you have other files from ALV that PyCorrFit cannot load, please create a new issue.
