### ISSUE TITLE
If .txt / .ascii file can be imorted in Pycorrfit ?

### ISSUE THREAD

**Issue by Bikashphy** [FCS-analysis/PyCorrFit#171]
Hi,
It will be very helpful if Pycorrfit software can open .txt format FCS data.

With Best Regards,
Bikash

**Comment by paulmueller** [comment]
PyCorrFit can open data as tab separated values (with a .csv extension). See section 3.3 of the documentation:
https://github.com/FCS-analysis/PyCorrFit/wiki/PyCorrFit_doc.pdf

**Comment by Bikashphy** [comment]
Thank You.

With Best Regards,
Bikash
