### ISSUE TITLE
Some unicode characters are not converted when using plot export with LaTeX

### ISSUE THREAD

**Issue by paulmueller** [FCS-analysis/PyCorrFit#179]
```
filename/title	
Model species	T+T+3D+3D
Model name	Separate 3D diffusion with double triplet (confocal)
Model ID	6043
Model function	CF_Gxyz_gauss_3D3DTT
Page number	3
Normalization	None

Parameters:
  n	25.0
  τ₁ [ms]	5.0
  τ₂ [ms]	1000.0
  F₁	0.5
  SP	5.0
  α (q₂/q₁)	1.0
  τ_trip₁ [µs]	1.0
  T₁	0.01
  τ_trip₂ [µs]	2.0
  T₂	0.01
  offset	0.0

Supplementary parameters:
  n₁	12.5
  n₂	12.5
```

**Comment by toubol** [comment]
More than a problem of conversion, you have a problem of underscore inside a text area and not a unicode error.
for exemple:
you have `\text{trip_1}`
you want `\text{trip$_1$}`
You have actually this problem for all the models with a second unicode character at the bottom or with text + unicode character at the bottom.
I have find a way to solve it. You'll get it really soon.
