### ISSUE TITLE
Error when opening Pycorrfit

### ISSUE THREAD

**Issue by tneg** [FCS-analysis/PyCorrFit#186]
Hello,

I've installed on my Ubuntu 18.04 System Pycorrfir via the pip command. However when I enter 'pycorrfit' in the terminal I get the following error message:

```
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/home/xxx/.local/bin/pycorrfit", line 7, in <module>
    from pycorrfit import Main
ImportError: cannot import name Main
```

What can I do to solve this?

**Comment by paulmueller** [comment]
I see, please try ``python -m pycorrfit``.

**Comment by paulmueller** [comment]
Please make sure to install PyCorrFit with Python 3. Python 2 is not supported anymore and you are probably encountering an old bug that has been fixed since the switch from Python 2 to Python 3.

**Comment by tneg** [comment]
Thanks a lot! The command `python**3** -m pycorrfit` did the trick!
