### ISSUE TITLE
Definition of the structural parameter

### ISSUE THREAD

**Issue by ESlenders** [FCS-analysis/PyCorrFit#195]
According to p. 20 of the manual, the structural parameter is defined as the square of the ratio of the height and the weight of the PSF. However, Eq. 12, a couple of lines below this definition, suggests that SP is just the ratio, not squared. I'd expect the latter to be the correct one. Could you confirm this?

Thanks.
Eli

**Comment by weidemann** [comment]
Correct. Structure Parameter is SP=z0/w0, whereby w0 is the 1/e^2-radius in xy and z0 the 1/e^2-radius along the optical axis z.

1/e^2 radius is the radius in which the Gaussian intensity dirstribution has decayed to 1/e^2 ~ 1/(2.7)^2 ~1/10th

**Comment by paulmueller** [comment]
Thanks for spotting that. I updated the manual.
